config/routes.rb
Rails.application.routes.draw do
  #root 'chatroom#index'
  resources :messages, only: [:create]
  mount ActionCable.server => '/cable'
  resources :tickets, only: %i[index show]
  namespace :api do
    namespace :v1 do
      resources :tickets, only: [ :create ]
    end
  end
  root "tickets#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/excavator.rb
class Excavator < ApplicationRecord
  belongs_to :ticket
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_one :excavator, dependent: :destroy
  validates :request_number, presence: true, uniqueness: true

  def self.convert_polygon(original_polygon)
    coordinates_str = original_polygon.match(/\(\((.*)\)\)/)[1]
    coordinates = coordinates_str.split(", ").map { |coord| coord.split(" ").map(&:to_f) }
    coordinates.map { |lon, lat| [ lon.round(3), lat.round(3) ] }
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :messages

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/api/v1/tickets_controller.rb
class Api::V1::TicketsController < ApplicationController
  protect_from_forgery with: :null_session
  def create
    Rails.logger.debug "Ticket Params: #{ticket_params.inspect}"
    @ticket = Ticket.new(ticket_params.except(:excavator_attributes))
    @ticket.build_excavator(ticket_params[:excavator_attributes])
    if @ticket.save
      render json: @ticket, status: :created
    else
      Rails.logger.debug "Ticket Errors: #{@ticket.errors.full_messages}"
      render json: @ticket.errors, status: :unprocessable_entity
    end
  end

  private

  def ticket_params
    params.require(:ticket).permit(
      :request_number, :reference_request_number, :version_number,
      :sequence_number, :request_type, :request_action, :request_taken_at, :legal_at,
      :response_due_at, :restake_at, :expiration_at, :primary_service_area_code,
      :type_of_work, :work_done_for, :project_duration, :project_start_date,
      :explosives, :underground_overhead, :horizontal_boring, :whitelined,
      :locate_instructions, :remarks, :well_known_text,
      digsite_info: [
        :lookup_by, :location_type,
        address_info: [
          :state, :county, :place,
          address: [ :address_num ],
          street: [ :prefix, :name, :type, :suffix ]
        ],
        near_street: [ :state, :county, :place ],
        intersection: [
          itoi: [ :state, :county, :place, :name, :type, :suffix ]
        ]
      ],
      additional_service_area_codes: [],
      excavator_attributes: [
        :company_name, :address, :city, :state, :zip, :excavator_type,
        :contact_name, :contact_phone, :contact_email, :field_contact_name,
        :field_contact_phone, :field_contact_email, :crew_onsite
      ]
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  def index
    @messages = Message.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = current_user.messages.build(message_params)
    if @message.save
      ActionCable.server.broadcast 'chatroom_channel', message: render_message(@message)
      head :ok
    else
      # Handle errors if save fails
      render json: { error: @message.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end

  def render_message(message)
    ApplicationController.render(partial: 'messages/message', locals: { message: message })
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    @tickets = Ticket.all
  end

  def show
    # options = {}
    # available_option_keys = [:first_option, :second_option, :third_option]
    # all_keys = params.keys.map(&:to_sym)
    # set_option_keys = all_keys & available_option_keys
    # set_option_keys.each do |key|
    #   options[key] = params[key]
    # end
    # options

    # Because Symbol objects in Ruby are not garbage collected, it is dangerous to convert user supplied parameters to symbols.
    # An attacker could send a series of requests with random keys that would be turned into symbols, quickly exhausting
    # your server's available memory and taking down your site.

    # There are two ways that this could could be fixed. The first would be to use slice to eliminate values from the params
    # hash that are not valid option keys. This would look something like:

    # params.slice(available_option_keys).each do |key|
    #   options[key] = params[key]
    # end

    @ticket = Ticket.find(params[:id])
    coordinates =  @ticket.well_known_text
    @coordinates = Ticket.convert_polygon(coordinates)
    @sample_coordinates = @coordinates.sample

    # @coordinates = [ [ 156922.3097, 6559238.263 ], [ 157424.9655, 6559462.937 ], [ 157837.7369, 6559395.169 ], [ 158078.2783, 6559284.668 ] ]
  end

  # def users_comments
  #   posts = Post.all
  #   comments = posts.map(&:comments).flatten
  #   @user_comments = comments.filter do |comment|
  #     comment.author.username == params[:username]
  #   end
  # end

  # This is a classic example of an "n+1" bug. The first line will retrieve all of the Post objects from the database,
  # but then the very next line will make an additional request for each Post to retrieve the corresponding Comment objects.
  # To make matters worse, this code is then making even more database requests in order to retrieve the Author of each Comment.

  # This can all be avoided by changing the first line in the method to:

  # posts = Post.includes(comments: [:author]).all

  # This will tell ActiveRecord to perform a database join between the tables for Post, Comment, and Author,
  # reducing the number of database requests to just one.
end

app/helpers/api/v1/tickets_helper.rb
module Api::V1::TicketsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/chatroom/index.html.erb
<!-- app/views/chatroom/index.html.erb -->
<h1>Chatroom</h1>

<div id="messages">
  <%= render @messages %>
</div>

<%= form_with model: Message.new, url: messages_path, local: true do |form| %>
  <%= form.text_field :content, id: "message-input", placeholder: "Type your message..." %>
  <%= form.submit "Send", id: "send-button" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "C Labs Demo" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
     <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
     integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
     crossorigin=""/>
      <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
     integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
     crossorigin=""></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/wicket@1.3.8/wicket.min.js"></script>
    <link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message">
  <strong><%= message.user.username %>:</strong> <%= message.content %>
</div>

app/views/tickets/index.html.erb
<h3>Tickets</h3 >
<hr>
<% if @tickets.present? %>
  <p>Reference Number </p>
  <ul>
    <% @tickets.each do |tkt| %>
      <li><%= link_to "#{tkt.request_number}", ticket_path(tkt) %></li>
    <% end %>
  </ul>
<% else %>
  <p>No tickets available</p>
<% end %>

app/views/tickets/show.html.erb
<h3>Ticket </h3>
<hr>
<p>Request Number: <%= @ticket.request_number %>
<p>Sequence Number: <%= @ticket.sequence_number %>
<p>Request Type: <%= @ticket.request_type %></p>
<p>Request Action: <%= @ticket.request_action %></p>
<p>Response Due Date: <%= @ticket.response_due_at.strftime("%B %d %Y") %></p>
<p>Service Area: <%= @ticket.primary_service_area_code %>, <%= @ticket.additional_service_area_codes.scan(/\w+/).join(", ") %></p>
<p>Digsite Info: <%= @ticket.well_known_text %></p>
<h3>Excavator Details</h3>
<hr>
<% if @ticket.excavator %>
  <p>Company: <%= @ticket.excavator.company_name %> </p>
  <p>Address: 
    <%= "#{@ticket.excavator.address}, #{@ticket.excavator.city}, #{@ticket.excavator.state}" %>
  </p>
  <p>Crew On Site: <%= @ticket.excavator.crew_onsite ? "Yes" : "No" %> </p>
<% end %>

<br/>
<div id="map" data-controller="map" data-map-target="map" data-wkt="<%= @coordinates %>" data-map-sample-value="<%= @sample_coordinates %>"  style="height: 400px;"></div>